require File.join(File.dirname(__FILE__), '..', '..', '..', '..', 'main', 'ruby', 'maven', 'tools', 'rails_project.rb')


describe Maven::Tools::RailsProject do

  before :each do
    @project = Maven::Tools::RailsProject.new("test")
  end
  
  it 'should load Gemfile from a simple rails application with applied defaults' do
    @project.load(File.join(File.dirname(__FILE__), 'Gemfile.simple'))
    @project.name "test"
    @project.add_defaults
    @project.to_xml.should == <<-XML
<project>
  <modelVersion>4.0.0</modelVersion>
  <groupId>rails</groupId>
  <artifactId>test</artifactId>
  <version>0.0.0</version>
  <name><![CDATA[test]]></name>
  <packaging>war</packaging>
  <repositories>
    <repository>
      <id>rubygems-releases</id>
      <url>http://gems.saumya.de/releases</url>
    </repository>
  </repositories>
  <pluginRepositories>
    <pluginRepository>
      <id>rubygems-releases</id>
      <url>http://gems.saumya.de/releases</url>
    </pluginRepository>
  </pluginRepositories>
  <dependencies>
    <dependency>
      <groupId>rubygems</groupId>
      <artifactId>rails</artifactId>
      <version>3.0.1</version>
      <type>gem</type>
    </dependency>
    <dependency>
      <groupId>rubygems</groupId>
      <artifactId>activerecord-jdbc-adapter</artifactId>
      <version>[0.0.0,)</version>
      <type>gem</type>
    </dependency>
    <dependency>
      <groupId>rubygems</groupId>
      <artifactId>jdbc-sqlite3</artifactId>
      <version>[0.0.0,)</version>
      <type>gem</type>
    </dependency>
    <dependency>
      <groupId>org.jruby</groupId>
      <artifactId>jruby-complete</artifactId>
      <version>@jruby.version@</version>
      <type>jar</type>
    </dependency>
    <dependency>
      <groupId>rubygems</groupId>
      <artifactId>bundler</artifactId>
      <version>[0.0.0,)</version>
      <type>gem</type>
    </dependency>
    <dependency>
      <groupId>org.jruby.rack</groupId>
      <artifactId>jruby-rack</artifactId>
      <version>1.0.9</version>
      <type>jar</type>
    </dependency>
  </dependencies>
  <properties>
    <gem.home>${project.build.directory}/rubygems</gem.home>
    <gem.includeRubygemsInTestResources>false</gem.includeRubygemsInTestResources>
    <gem.path>${project.build.directory}/rubygems</gem.path>
    <jetty.version>7.4.2.v20110526</jetty.version>
    <jruby.plugins.version>@project.version@</jruby.plugins.version>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <rails.env>development</rails.env>
  </properties>
  <build>
    <plugins>
      <plugin>
        <groupId>de.saumya.mojo</groupId>
        <artifactId>bundler-maven-plugin</artifactId>
        <version>${jruby.plugins.version}</version>
        <executions>
          <execution>
            <goals>
              <goal>install</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>de.saumya.mojo</groupId>
        <artifactId>rails3-maven-plugin</artifactId>
        <version>${jruby.plugins.version}</version>
        <executions>
          <execution>
            <id>in_phase_validate</id>
            <phase>validate</phase>
            <goals>
              <goal>initialize</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-war-plugin</artifactId>
        <version>2.1.1</version>
        <configuration>
          <webResources>
            <resource>
              <directory>public</directory>
            </resource>
            <resource>
              <directory>.</directory>
              <includes>
                <include>app/**</include>
                <include>config/**</include>
                <include>lib/**</include>
                <include>vendor/**</include>
                <include>Gemfile</include>
              </includes>
              <targetPath>WEB-INF</targetPath>
            </resource>
            <resource>
              <directory>${gem.path}</directory>
              <includes>
                <include>gems/**</include>
                <include>specifications/**</include>
              </includes>
              <targetPath>WEB-INF/gems</targetPath>
            </resource>
            <resource>
              <directory>${gem.path}-bundler-maven-plugin</directory>
              <includes>
                <include>specifications/**</include>
              </includes>
              <targetPath>WEB-INF/gems</targetPath>
            </resource>
          </webResources>
        </configuration>
      </plugin>
    </plugins>
  </build>
  <profiles>
    <profile>
      <id>development</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
    </profile>
    <profile>
      <id>test</id>
      <activation>
        <property>
          <name>rails.env</name>
          <value>test</value>
        </property>
      </activation>
    </profile>
    <profile>
      <id>production</id>
      <activation>
        <property>
          <name>rails.env</name>
          <value>production</value>
        </property>
      </activation>
      <properties>
        <gem.home>${project.build.directory}/rubygems-production</gem.home>
        <gem.path>${project.build.directory}/rubygems-production</gem.path>
      </properties>
    </profile>
    <profile>
      <id>war</id>
      <build>
        <plugins>
          <plugin>
            <groupId>org.mortbay.jetty</groupId>
            <artifactId>jetty-maven-plugin</artifactId>
            <version>${jetty.version}</version>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>run</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <build>
        <plugins>
          <plugin>
            <groupId>org.mortbay.jetty</groupId>
            <artifactId>jetty-maven-plugin</artifactId>
            <version>${jetty.version}</version>
            <configuration>
              <connectors>
                <connector implementation="org.eclipse.jetty.server.nio.SelectChannelConnector">
                  <port>8080</port>
                </connector>
                <connector implementation="org.eclipse.jetty.server.ssl.SslSelectChannelConnector">
                  <port>8443</port>
                  <keystore>${project.basedir}/src/test/resources/server.keystore</keystore>
                  <keyPassword>123456</keyPassword>
                  <password>123456</password>
                </connector>
              </connectors>
              <webAppConfig>
                <overrideDescriptor>${project.build.directory}/jetty/override-${rails.env}-web.xml</overrideDescriptor>
              </webAppConfig>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>executable</id>
      <pluginRepositories>
        <pluginRepository>
          <id>kos</id>
          <url>http://opensource.kantega.no/nexus/content/groups/public/</url>
        </pluginRepository>
      </pluginRepositories>
      <build>
        <plugins>
          <plugin>
            <groupId>org.simplericity.jettyconsole</groupId>
            <artifactId>jetty-console-maven-plugin</artifactId>
            <version>1.42</version>
            <executions>
              <execution>
                <goals>
                  <goal>createconsole</goal>
                </goals>
                <configuration>
                <!--
                                  see http://simplericity.com/2009/11/10/1257880778509.html for more info
                -->
                <!--
		  <backgroundImage>${basedir}/src/main/jettyconsole/puffin.jpg</backgroundImage>
		  <additionalDependencies>
		    <additionalDependency>
		      <artifactId>jetty-console-winsrv-plugin</artifactId>
		    </additionalDependency>
		    <additionalDependency>
		      <artifactId>jetty-console-requestlog-plugin</artifactId>
		    </additionalDependency>
		    <additionalDependency>
		      <artifactId>jetty-console-log4j-plugin</artifactId>
		    </additionalDependency>
		    <additionalDependency>
		      <artifactId>jetty-console-jettyxml-plugin</artifactId>
		    </additionalDependency>
		    <additionalDependency>
		      <artifactId>jetty-console-ajp-plugin</artifactId>
		    </additionalDependency>
		    <additionalDependency>
		      <artifactId>jetty-console-gzip-plugin</artifactId>
		    </additionalDependency>
		    <additionalDependency>
		      <artifactId>jetty-console-startstop-plugin</artifactId>
		    </additionalDependency>
		  </additionalDependencies>

                -->
                </configuration>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
</project>
XML
  end

  it 'should load Gemfile from a rails application"' do
    @project.load(File.join(File.dirname(__FILE__), 'Gemfile.rails'))
    @project.to_xml.should == <<-XML
<project>
  <modelVersion>4.0.0</modelVersion>
  <groupId>rails</groupId>
  <artifactId>test</artifactId>
  <version>0.0.0</version>
  <packaging>war</packaging>
  <dependencies>
    <dependency>
      <groupId>rubygems</groupId>
      <artifactId>rails</artifactId>
      <version>3.0.1</version>
      <type>gem</type>
    </dependency>
    <dependency>
      <groupId>rubygems</groupId>
      <artifactId>activerecord-jdbc-adapter</artifactId>
      <version>[0.0.0,)</version>
      <type>gem</type>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>de.saumya.mojo</groupId>
        <artifactId>bundler-maven-plugin</artifactId>
        <dependencies>
          <dependency>
            <groupId>rubygems</groupId>
            <artifactId>jdbc-sqlite3</artifactId>
            <version>[0.0.0,)</version>
            <type>gem</type>
          </dependency>
          <dependency>
            <groupId>rubygems</groupId>
            <artifactId>rspec</artifactId>
            <version>[0.0.0,)</version>
            <type>gem</type>
          </dependency>
          <dependency>
            <groupId>rubygems</groupId>
            <artifactId>jdbc-mysql</artifactId>
            <version>[0.0.0,)</version>
            <type>gem</type>
          </dependency>
        </dependencies>
      </plugin>
    </plugins>
  </build>
  <profiles>
    <profile>
      <id>development</id>
      <dependencies>
        <dependency>
          <groupId>rubygems</groupId>
          <artifactId>jdbc-sqlite3</artifactId>
          <version>[0.0.0,)</version>
          <type>gem</type>
        </dependency>
        <dependency>
          <groupId>rubygems</groupId>
          <artifactId>rspec</artifactId>
          <version>[0.0.0,)</version>
          <type>gem</type>
        </dependency>
      </dependencies>
    </profile>
    <profile>
      <id>test</id>
      <dependencies>
        <dependency>
          <groupId>rubygems</groupId>
          <artifactId>rspec</artifactId>
          <version>[0.0.0,)</version>
          <type>gem</type>
        </dependency>
      </dependencies>
    </profile>
    <profile>
      <id>production</id>
      <dependencies>
        <dependency>
          <groupId>rubygems</groupId>
          <artifactId>jdbc-mysql</artifactId>
          <version>[0.0.0,)</version>
          <type>gem</type>
        </dependency>
      </dependencies>
    </profile>
  </profiles>
</project>
XML
  end
end
