#set( $symbol_slot = '#' )
#if($railsVersion.substring(0,1) == '2')
${symbol_slot} This file was generated by the "jdbc" generator, which is provided
${symbol_slot} by the activerecord-jdbc-adapter gem.
${symbol_slot}
${symbol_slot} This file allows you to use Rails' various db:* tasks with JDBC.
if defined?(JRUBY_VERSION)
  require 'jdbc_adapter'
  require 'jdbc_adapter/rake_tasks'
end
#end