# overwrite via cli -Djruby.versions=1.6.7
properties['jruby.versions'] = ['1.5.6','1.6.5.1','1.6.7.2','1.7.0.preview1'].join(',')
# overwrite via cli -Djruby.use18and19=false
properties['jruby.18and19'] = true

