#set( $symbol_slot = '#' )
#if($railsVersion.substring(0,1) == '2')
${symbol_slot} This file was generated by the "jdbc" generator, which is provided
${symbol_slot} by the activerecord-jdbc-adapter gem.
${symbol_slot}
${symbol_slot} This file allows the JDBC drivers to be hooked into ActiveRecord
${symbol_slot} such that you don't have to change anything else in your Rails
${symbol_slot} application.
require 'jdbc_adapter' if defined?(JRUBY_VERSION)
#end
